on:
  push:
    branches:
      - master

jobs:
  run:
    name: Apply GorillaStack config templates
    container: gorillastack/github-actions-base:latest
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@master

    - name: Apply templates
      uses: './'
      with:
        action: apply