on: [push]

jobs:
  run:
    name: Validate GorillaStack config templates
    container: gorillastack/github-actions-base:latest
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master

    - name: Validate templates
      uses: './'
